# TODO: remove (will be part of pre-commit hook)

name: 'Lint'
description: 'Runs ruff on the target app repository'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    # Reusable actions can't use setup-python's cache because it looks for the running repo's deps
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-soar-ci
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Checkout App Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: 'Lint App Repo'
      run: |
        cd ${{ github.action_path }}/../..
        make lint APP_FOLDER=${{ github.workspace }}
      shell: bash
