name: 'Lint'
description: 'Runs flake8/isort on the target app repository'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Checkout App Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: 'Lint App Repo'
      run: |
        cd ${{ github.action_path }}/../..
        make lint APP_FOLDER=${{ github.workspace }}
      shell: bash
