name: 'Semgrep'
description: 'Runs semgrep on the target app repository'
inputs:
  SEMGREP_DEPLOYMENT_ID:
    description: Semgrep account ID
    required: true
  SEMGREP_APP_TOKEN:
    description: Semgrep account token to access configured rules
runs:
  using: 'composite'
  steps:
    - name: Checkout App Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.REF }}
        repository: ${{ inputs.REPOSITORY }}
    - name: Copy .semgrepignore to workspace
      run: |
        if [ ! -f ${{ github.workspace}}/.semgrepignore ]; then
          cp ${{ github.action_path }}/.semgrepignore ${{ github.workspace }}
        fi
        if [ ! -d "${{ github.workspace }}/semgrep" ]; then
          mkdir ${{ github.workspace }}/semgrep
        fi
        cp ${{ github.action_path }}/../../semgrep/rules/python/**/*.yaml ${{ github.workspace }}/semgrep
      shell: bash
    - name: 'Semgrep scan'
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          semgrep
          p/python
          r/typescript.react.security.audit.react-dangerouslysetinnerhtml.react-dangerouslysetinnerhtml
        # Fetches configured rules from Semgrep account
        # publishDeployment: ${{ inputs.SEMGREP_DEPLOYMENT_ID }}
        # publishToken: ${{ inputs.SEMGREP_APP_TOKEN }}
