# Pre-commit hooks.   Configuration examples at https://pre-commit.com/
repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  # Python linting and formatting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.9.3'
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # Shell linting and formatting
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-2
    hooks:
      - id: shfmt-docker  # Docker image (requires Docker to run)

  # Security scanning with semgrep
  - repo: https://github.com/returntocorp/semgrep
    rev: 'v1.107.0'
    hooks:
      - id: semgrep
        args: [
          '--config', 'p/python',  # Built-in Python rules
          '--config', 'semgrep'    # Look for our other rules
        ]
