# Pre-commit hooks.   Configuration examples at https://pre-commit.com/
minimum_pre_commit_version: '4.0.0'
repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  # Python linting and formatting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.14.2'
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # Shell linting and formatting
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: ["-x"]

  # Shell formatting
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt-docker  # Docker image (requires Docker to run)
