- id: build-docs
  name: build docs
  description: Builds and checks application documentation
  entry: pre-commit/build_docs
  language: script
  types: [markdown, json]
  always_run: true
  pass_filenames: false
- id: copyright
  name: update copyright headers
  description: Updates copyright headers for application files
  entry: pre-commit/copyright
  language: script
  always_run: true
  pass_filenames: false
- id: package-app-dependencies
  name: package app dependencies
  description: Packages application dependencies
  entry: pre-commit/package_app_dependencies
  language: script
  files: '^requirements.txt$'
