- id: build-docs
  name: build docs
  description: Builds and checks application documentation
  entry: build-docs
  language: python
  pass_filenames: false
- id: copyright
  name: update copyright headers
  description: Updates copyright headers for application files
  entry: copyright-updates
  language: python
  pass_filenames: false
- id: package-app-dependencies
  name: package app dependencies
  description: Packages application dependencies
  entry: package_app_dependencies.sh
  language: python
  files: '^requirements.txt$'
- id: generate-notice
  name: generate notice file
  description: Generates notice file based on app dependencies
  entry: generate-notice
  language: python
  pass_filenames: false
- id: release-notes
  name: update release notes
  description: Updates release notes for connector
  language: python
  entry: release-notes
  pass_filenames: false
- id: static-tests
  name: Run static tests
  description: Runs tests to validate app json, check code correctness, and detect security vulnerabilities
  entry: static-tests
  language: python
  pass_filenames: false
