-   id: org-hook
    name: org-wide hooks
    language: script
    entry: pre-commit/run-org-hooks
    verbose: true
-   id: package-app-dependencies
    name: package app dependencies
    files: '^requirements.txt$'
    language: script
    entry: pre-commit/package_app_dependencies
    verbose: true
-   id: readme-check # TODO: Move to org hooks
    name: readme check
    language: script
    entry: github-actions/start-release/readme_check.py # TODO: Clean up this stuff (move out of start-release, etc...) -> part of doc ticket
    pass_filenames: false
