- id: package-app-dependencies
  name: package app dependencies
  description: Packages application dependencies
  entry: pre-commit/package_app_dependencies
  language: python
  files: '^requirements.txt$'
