-   id: org-hook
    name: org-wide hooks
    language: script
    entry: pre-commit/run-org-hooks
    verbose: true
-   id: package-app-dependencies
    name: package app dependencies
    files: '^requirements.txt$'
    language: script
    entry: pre-commit/package_app_dependencies
    verbose: true
-   id: readme_check
    name: readme check
    language: script
    entry: github-actions/start-release/build_docs.py
