- id: build-docs
  name: build docs
  description: Builds and checks application documentation
  entry: pre-commit/build_docs
  language: script
  types: [markdown, json]
  pass_filenames: false
- id: copyright
  name: update copyright headers
  description: Updates copyright headers for application files
  entry: pre-commit/copyright
  language: script
  pass_filenames: false
- id: package-app-dependencies
  name: package app dependencies
  description: Packages application dependencies
  entry: pre-commit/package_app_dependencies
  language: script
  files: '^requirements.txt$'
- id: static-tests
  name: Run static tests
  description: Runs tests to validate app json, assets, test playbooks and security vulnerabilities
  entry: pre-commit/static_tests
  language: script
  pass_filenames: false
