[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "local-hooks"
version = "0.1.0"
dependencies = ["jinja2", "mdformat", "jsonschema", "lxml", "django<5"]
