#!/usr/bin/env bash

APP_DIR=$(pwd)
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

function package_py2_app_dependencies() {
  echo 'Python2 supported app detected'
  if ! pip2 --version &> /dev/null; then
    echo 'Please ensure pip2 is installed'
    exit 1
  fi
  python "$SCRIPT_DIR/package_app_dependencies.py" "$APP_DIR" pip2 pip_dependencies
}


if ! jq --help &> /dev/null; then
  echo 'Please ensure jq is installed (eg, brew install jq)'
  exit 1
fi

app_json="$(find ./*.json ! -name '*.postman_collection.json'| head -n 1)"
app_py_version="$(jq .python_version "$app_json")"
if [[ "$app_py_version" == 'null' ]]; then
  app_py_version='"2.7"'
fi

if [[ "$app_py_version" == '"2.7"' ]]; then
  package_py2_app_dependencies
  exit $?
fi

if ! docker info &> /dev/null; then
  echo 'Please ensure Docker is installed and running on your machine'
  exit 1
fi

pip3_dependencies="$(jq .pip3_dependencies "$app_json")"
if [[ "$pip3_dependencies" == 'null' ]]; then
  pip3_dependencies_key='pip_dependencies'
else
  pip3_dependencies_key='pip3_dependencies'
  if [[ "$(jq .pip_dependencies "$app_json")" != 'null' ]]; then
    package_py2_app_dependencies
  fi
fi

docker run --rm -v "$APP_DIR":/src -v "$SCRIPT_DIR":/pre-commit/ -w "$SCRIPT_DIR" \
  quay.io/pypa/manylinux2014_x86_64 /bin/bash -c \
   "/opt/python/cp39-cp39/bin/python /pre-commit/package_app_dependencies.py \
   /src /opt/python/cp36-cp36m/bin/pip $pip3_dependencies_key --repair_wheels"
