#!/usr/bin/env python3

import os
import sys

HERE = os.path.dirname(os.path.realpath(__file__))


def main():
    """ Main entrypoint. """
    cfg = os.path.join(HERE, 'orghooks.yaml')
    print(sys.argv[1:])
    cmd = ['pre-commit', 'run', '--config', cfg, '--files'] + sys.argv[1:]
    os.execvp(cmd[0], cmd)


if __name__ == '__main__':
    exit(main())
