name: 'Integration Tests'
description: 'Runs the integration tests for the given app repo through AWS CodeBuild'
inputs:
  AWS_ROLE_ARN:
    description: 'Role to assume to run the CodeBuild project'
    required: true
  AWS_REGION:
    description: 'Region of the CodeBuild project'
    default: 'us-west-2'
    required: false
  CODE_BUILD_PROJECT:
    description: 'Name of the codebuild project'
    default: 'soar-connector-integration-tests'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 'Checkout App Repo'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: 'Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v1.6.1
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE_ARN }}
    - name: 'Run CodeBuild Project'
      uses: 'aws-actions/aws-codebuild-run-build@v1.0.4'
      with:
        project-name: ${{ inputs.CODE_BUILD_PROJECT }}
        env-vars-for-codebuild: |
          APP_REPO,
          APP_REPO_BRANCH,
          APP_TESTS_BRANCH
      env:
        APP_REPO: ${{ github.event.repository.name }}
        APP_REPO_BRANCH: ${{ github.ref_name }}
        APP_TESTS_BRANCH: ${{ github.ref_name }}
