name: "Package App Dependencies"
description: "Bundle an app's Python dependency wheels into the repo"
inputs:
  GITHUB_TOKEN:
    description: "PAT used to write to the target repo"
    required: true
  python-version:
    description: "Python version used for bundling wheels"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Check pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip${{ inputs.python-version }}-soar-app-ci
    - name: Checkout app repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Install Python dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install requests
    - name: Package app dependencies for this Python version
      shell: bash
      run: |
        python ${{ github.action_path }}/main.py
    - name: Post a comment summarizing any warnings during the packaging process
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: summary_comment.md
    - name: Commit the updated dependencies if necessary
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        git config user.name "splunk-soar-connectors-admin"
        git config user.email "admin@splunksoar"
        git add "*.json"
        git add "wheels"
        git diff --quiet && git diff --staged --quiet || (git commit -m "Bundle dependency wheels"; git push)
