name: 'Package App Dependencies'
description: "Bundle an app's Python dependency wheels into the repo"
inputs:
  GITHUB_TOKEN:
    description: 'PAT used to write to the target repo'
    required: true
  python-version:
    description: 'Python version used for bundling wheels'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Check pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip${{ inputs.python-version }}-soar-app-ci
    - name: Checkout app repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Package app dependencies for this Python version
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        which auditwheel || echo "auditwheel not installed"
        python ${{ github.action_path }}/main.py
