name: 'Package App Dependencies'
description: "Bundle an app's Python dependency wheels into the repo"
inputs:
  GITHUB_TOKEN:
    description: 'PAT used to write to the target repo'
    required: true
  HOST_PYTHON_VERSION:
    description: 'The Python version used to execute the GitHub action'
    required: true
    default: 'cp39-cp39'
  TARGET_PYTHON_VERSIONS:
    description: 'Comma-separated list of Python versions to bundle wheels for'
    required: true
    default: 'cp36-cp36m,cp39-cp39'
runs:
  using: 'docker'
  image: 'docker://quay.io/pypa/manylinux2014_x86_64'
  entrypoint: "/opt/python/${{ inputs.HOST_PYTHON_VERSION }}/bin/python"
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    HOST_PYTHON_VERSION: ${{ inputs.HOST_PYTHON_VERSION }}
    TARGET_PYTHON_VERSIONS: ${{ inputs.TARGET_PYTHON_VERSIONS }}
  args:
    - main.py
