name: 'Review Release'
description: 'Determines whether a given app release is automatically approved for Splunkbase upload or if it requires manual approval.'
inputs:
  github_token:
    description: 'Token used to authenticate with the GitHub REST API'
    required: true
outputs:
  manual_review_required:
    description: "true/false depending on if the the release requires manual review"
    value: ${{ steps.review_release.outputs.manual_review_required }}
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    # Reusable actions can't use setup-python's cache because it looks for the running repo's deps
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-soar-ci-release
    - name: 'Install Dependencies'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r "${{ github.action_path }}/../scripts/review_release/requirements.txt"
    - name: Checkout App Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: 'Update Commit Status'
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: |
        cd ${{ github.action_path }}/..
        python -m scripts.review_release.put_commit_status ${{ github.repository }} ${{ github.sha }} \
          -s pending -d 'Pending review' -t "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    - name: 'Review Release'
      id: review_release
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        APP_REPO: ${{ github.repository }}
      shell: bash
      run: |
        cd ${{ github.action_path }}/..
        exit_code=0
        python -m scripts.review_release.main || exit_code=$?
        if [[ $exit_code -eq 0 ]]; then
          echo "{manual_review_required}={false}" >> $GITHUB_OUTPUT
        elif [[ $exit_code -eq 1 ]]; then
          echo "{manual_review_required}={true}" >> $GITHUB_OUTPUT
        else
          exit $exit_code
        fi
