name: 'SOAR App CI'
description: 'CI steps common to SOAR Apps'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: 'Check PIP Cache'
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/github-actions/**/requirements.txt') }}
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Checkout App Repo
      uses: actions/checkout@v2
      with:
        path: 'src'
        ref: ${{ github.ref }}
    - name: 'Lint App Repo'
      run: |
        cd ${{ github.action_path }}/../..
        make lint APP_FOLDER=${{ github.workspace }}/src
      shell: bash
