# Ruff linting
[tool.ruff]
line-length = 145
target-version = "py39"

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "C90",
    "A",
    "UP",
    "B",
    "C4",
    "RET",
    "SIM",
    "RUF",
    "PLC",
    "PLE",
    "PLW",
    "PT",
    "T201",
]

# Ignore same relevant rules as we did to with tox.ini
ignore = [
    "F403",
    "F405",
    "E731",
    "E201",
    "E202",
    "E203",
    "E701",
    "E722",
    "D",
]

# Keep complexity below 28
[tool.ruff.lint.mccabe]
max-complexity = 28

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# HTML linting
[tool.djlint]
profile = "django"
extension = "html"
indent = 2

# Markdown linting
[tool.mdformat]
wrap = true
number = true

# Semgrep configuration
[tool.semgrep]
config = [
    "p/python", # Built-in Python rules
    "semgrep", # Look for our other rules
    "r/typescript.react.security.audit.react-dangerouslysetinnerhtml.react-dangerouslysetinnerhtml" # TypeScript React security rule
]
ignore-patterns = [
    "node_modules/",
    "build/",
    "dist/",
    "vendor/",
    "env/",
    ".env/",
    "venv/",
    ".venv/",
    ".tox/",
    "*.min.js",
    "test/",
    "tests/",
    "*_test.go",
    ".semgrep",
    "wheels/",
    ".html",
    "*.md",
    "*.svg"
]
