# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_TOOLS_REPO: phantomcyber/dev-cicd-tools
      CI_TOOLS_BRANCH: main
      CI_TOOLS_DIR: dev-cicd-tools
      LINT_CONFIG: dev-cicd-tools/lint-configs/tox.ini
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.CI_TOOLS_REPO }}
        path: ${{ env.CI_TOOLS_DIR }}
        ref: ${{ env.CI_TOOLS_BRANCH }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    # Reusable actions can't use setup-python's cache because it looks for the running repo's deps
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-soar-ci
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8 and isort
      run: |
        flake8 . --config $LINT_CONFIG
        isort . --check-only --settings-path $LINT_CONFIG
