[tool.ruff]
line-length = 145
target-version = "py39"

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "C90",
]

# Ignore same rules as we used to with tox.ini
ignore = [
    "F403",
    "F405",
    "E731",
    "E201",
    "E202",
    "E203",
    "E701",
    "E722",
    "D",
]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.mccabe]
max-complexity = 28
