name: Review Release
on:
  workflow_call:
    inputs:
      task_token:
        type: string
        required: true
        description: 'Task token to resume the paused StepFunction workflow orchestrating the app release'
      aws_region:
        type: string
        required: false
        description: 'Region of the workflow'
        default: 'us-west-2'
    secrets:
      resume_release_role_arn:
        required: true
jobs:
  review_release:
    runs-on: ubuntu-latest
    outputs:
      manual_review_required: ${{ steps.review_release.outputs.manual_review_required }}
    steps:
      - id: review_release
        uses: 'phantomcyber/dev-cicd-tools/github-actions/review-release@main'
        with:
          github_token: ${{ secrets.github_token }}
  manual_review:
    needs: [review_release]
    if: needs.review_release.outputs.manual_review_required == 'true'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: exit 0
  approve_release:
    needs: [review_release, manual_review]
    if: always() && (needs.manual_review.result == 'success' || (needs.review_release.result == 'success' && needs.manual_review.result == 'skipped'))
    runs-on: ubuntu-latest
    steps:
      - uses: 'phantomcyber/dev-cicd-tools/github-actions/resume-release@main'
        with:
          github_token: ${{ secrets.github_token }}
          approved: true
          task_token: ${{ inputs.task_token }}
          iam_role_arn: ${{ secrets.resume_release_role_arn }}
          aws_region: ${{ inputs.aws_region }}
  reject_release:
    needs: [manual_review]
    if: always() && needs.manual_review.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - uses: 'phantomcyber/dev-cicd-tools/github-actions/resume-release@main'
        with:
          github_token: ${{ secrets.github_token }}
          approved: false
          task_token: ${{ inputs.task_token }}
          iam_role_arn: ${{ secrets.resume_release_role_arn }}
          aws_region: ${{ inputs.aws_region }}
