name: Test Pre-Commit Hooks

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pre-commit/dev-requirements.txt
      - name: Run Tests
        working-directory: local_hooks
        run: pytest tests
