name: Test Start Release

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: pip
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y tidy
          wget https://github.com/jgm/pandoc/releases/download/3.6.2/pandoc-3.6.2-1-amd64.deb
          sudo dpkg -i pandoc-3.6.2-1-amd64.deb
          python -m pip install --upgrade pip
          pip install -r github-actions/start-release/requirements.txt
          pip install -r github-actions/start-release/dev-requirements.txt
      - name: Run Tests
        working-directory: github-actions/start-release
        run: pytest tests
