name: Test Review Release

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Export Requirements File Path'
        run: |
          echo "REQUIREMENTS_FILE_PATH=github-actions/scripts/review_release/requirements.txt" >> $GITHUB_ENV
          echo "DEV_REQUIREMENTS_FILE_PATH=github-actions/scripts/dev-requirements.txt" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: |
            ${{ env.REQUIREMENTS_FILE_PATH }}
            ${{ env.DEV_REQUIREMENTS_FILE_PATH }}
      - name: Install dependencies
        run: |
          pip install -r "${{ env.REQUIREMENTS_FILE_PATH }}"
          pip install -r "${{ env.DEV_REQUIREMENTS_FILE_PATH }}"
      - name: Run Tests
        working-directory: github-actions
        run: pytest scripts/tests/test_review_release.py
